# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7527b8bf98d16fa03a44ab47f848c1af7d0761aad4aff7255b4e81ee12e29969aa919c72b25542f329c67d475bc864570bff22d4a350bdf862f8aa99f3541179

test:
  secret_key_base: 3cb5acea1ba22d50e8358943ce85aaa1ed5f38ba48163970255ee59720ee1b9c2ba25425f8d65e2612dbaca1941eb5a61e9f53123a0307f09445e04e1fa9ef17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
